name: tapapp_flutter
description: Flutter conversion of the TapCard Expo app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  go_router: ^14.2.1
  mobile_scanner: ^6.0.2
  share_plus: ^10.0.2
  intl: ^0.18.1
  qr_flutter: ^4.0.0
  url_launcher: ^6.1.10
  permission_handler: ^11.3.0
  media_store_plus: ^0.1.3
  path_provider: ^2.1.5

  # 🔹 NEW Firebase + Google Login
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.10





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/google_logo.svg

  fonts:
    - family: NataSans
      fonts:
        - asset: assets/fonts/NataSans-Regular.ttf
